language: python
sudo: false

env:
    - TOX_ENV=py26-django15
    - TOX_ENV=py26-django16
    - TOX_ENV=py26-django17
    - TOX_ENV=py26-django18
    - TOX_ENV=py27-django15
    - TOX_ENV=py27-django16
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script: tox -e $TOX_ENV
